### ISSUE TITLE
Folders and files invisible

### ISSUE THREAD

**Issue by jorasso** [slack-theme/visual-studio-code#10]
Folders and files in dropdown navigation bar at the top are mostly invisible (see attached gif).
![slack_theme](https://user-images.githubusercontent.com/1930216/60189202-dae7fe80-9830-11e9-8962-5c553258d642.gif)

**Comment by felipemendes** [comment]
This will be fix on next update. Thanks for your help @jorasso :)

**Comment by jorasso** [comment]
My pleasure! I tried to fix it myself to come here with the solution, not just an issue report, but I wasn't able to find the proper option! 

Thanks for your great work @felipemendes !

**Comment by felipemendes** [comment]
That's okay. I like doing these things, but I could not fix it either cause this problem did not happen to me: /

Dropdown colors are normal for me. Tried on Mac OS and Windows 10, like attached files:

![mac](https://user-images.githubusercontent.com/3712089/60477702-6826bb00-9c56-11e9-9a66-89a343760ed7.gif)

![windows](https://user-images.githubusercontent.com/3712089/60477703-69f07e80-9c56-11e9-808b-5f49ff15c7ce.png)

**Comment by jorasso** [comment]
I can confirm it started working for me too... I have no idea what happened. I didn't installed or uninstalled any new plugins or extensions. Maybe VS Code autoupdated :)

But I am really happy it works 👍

**Comment by felipemendes** [comment]
That's weird :/ but good to know that it worked :)
