### ISSUE TITLE
Hoth editorSuggestWidget text unreadable

### ISSUE THREAD

**Issue by vwchu** [slack-theme/visual-studio-code#11]
Current Hoth theme Intellisense menu text is unreadable, white-text on white-background.
Should add the following to Hoth theme: 

```json
{
  "editorSuggestWidget.foreground": "#36373B",
  "editorSuggestWidget.highlightForeground": "#36373B"
}
```

**Comment by felipemendes** [comment]
Just fixed and pushed to v1.9.10.
Thanks for your help!
