### ISSUE TITLE
[Ochin] Master issue for fixing readability in various use scenarios

### ISSUE THREAD

**Issue by xunnanxu** [slack-theme/visual-studio-code#18]
In some cases when Ochin is enabled, it may make some of the UI unreadable. This is the master issue to track those fixes.

**Comment by xunnanxu** [comment]
Hi @felipemendes Could you update the VSC marketplace version now that these are merged? Thanks.

**Comment by felipemendes** [comment]
Hi, @xunnanxu
I just published a new version with these modifications. Thanks for notifying :)

**Comment by xunnanxu** [comment]
Thanks for the prompt response! @felipemendes
