### ISSUE TITLE
How to change color of mouse pointer

### ISSUE THREAD

**Issue by e96wic** [slack-theme/visual-studio-code#24]
Hi @felipemendes,

thanks for the great theme! Unfortunatly I cannot really see my mouse pointer with the ochin theme. White pointer on white background. How can I change that / what's the setting called? I already put about 2 hours into that :/ 

![image](https://user-images.githubusercontent.com/13048266/105750177-b12f1600-5f44-11eb-870d-3f9b80ec5cc0.png)

**Comment by felipemendes** [comment]
Hey @e96wic 

Thanks for your feedback :)

I really can't tell you how to fix this. I will check it and reach you back or I will try to fix

**Comment by felipemendes** [comment]
Hey @e96wic 

For this issue, the fix settings isn't on theme properties. It happens due how ochin's base theme is setup.
Property `uiTheme` on `package.json` is set to `vs-dark`, since its colors are brighter, I think we can change it to only `vs`.

Hopefully, it won't mess up other elements

**Comment by e96wic** [comment]
@felipemendes Awesome, thanks!
