### ISSUE TITLE
Autocomplete matching substring textcolor is not readable

### ISSUE THREAD

**Issue by rphl** [slack-theme/visual-studio-code#3]
The color for a matching substring in the Autocomplete-Popup is not readable.

<img width="513" alt="bildschirmfoto 2018-05-22 um 10 50 02" src="https://user-images.githubusercontent.com/97642/40352136-653da63e-5dae-11e8-90e3-d4f5cc574f9d.png">

**Comment by felipemendes** [comment]
Thanks for your feedback, Raphael. It'll be fixed
