### ISSUE TITLE
Unstaged file color very dim in the editor

### ISSUE THREAD

**Issue by nikeshparajuli** [slack-theme/visual-studio-code#30]
macOS 11.3.1
vscode 1.56.2

First of all, thank you so much for the theme. They are all very cool!

I noticed a small bug where most of the color palettes except Ochin and Dark show very whiteish color for files that have changed and are unstaged. As you can see, I'm using Aubergine and the filename text color looks completely normal after I stage my changes. I also checked out Ochin and it seems to handle this pretty well for both staged and unstaged files. Maybe we need a similar functionality for other ones. I hope you'll look into this.

Before staging changes:
![1](https://user-images.githubusercontent.com/47485043/118541896-43d80880-b720-11eb-97ce-7ac10eaf1576.png)

After staging changes:
![2](https://user-images.githubusercontent.com/47485043/118541910-476b8f80-b720-11eb-90c7-eccdb14c6a26.png)

**Comment by nikeshparajuli** [comment]
I could also create a PR with the fix if you want.. unfortunately I don't have write access to the repo.

**Comment by felipemendes** [comment]
Hey, @nikeshparajuli 
Thanks for your feedback :)

Not sure why you can't open a PR, those access are grant to everyone. Could you please try it again? Or if you already know how to fix it, please tell me.

Otherwise, I will try to figure this out

**Comment by felipemendes** [comment]
This perfectly fit all issues. Just merged [#31](https://github.com/slack-theme/visual-studio-code/pull/31)

**Comment by nikeshparajuli** [comment]
Awesome!
